version: 2.1
orbs:
    snyk: snyk/snyk@1.1.2
jobs:
    build:
        docker:
            - image: circleci/node:latest
        steps:
            - checkout
            - run: npm install
            - snyk/scan:
                fail-on-issues: true
                monitor-on-build: true
                severity-threshold: high
                token-variable: 7338949a-729f-4ee6-9808-9b3f2b953df5
workflows:
    version: 2
    build_and_test:
        jobs:
        - build
